force-brf/main/objects/brf_BatchApexErrorLog__c/brf_BatchApexErrorLog__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error Log</label>
    <nameField>
        <displayFormat>JOB-{00000000}</displayFormat>
        <label>Batch Apex Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>JobCreatedDate__c</fullName>
    <label>Job Created Date</label>
    <type>DateTime</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobErrors__c.field-meta.xml
<CustomField>
    <fullName>JobErrors__c</fullName>
    <label>Job Errors</label>
    <summaryForeignKey>brf_BatchApexError__c.BatchApexErrorLog__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <externalId>true</externalId>
    <label>Job Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-brf/main/classes/brf_BatchableErrorsComponentController.cls
/**
 * Controller queries for failed jobs and allows component to start retry jobs
 **/
public with sharing class brf_BatchableErrorsComponentController {

    @AuraEnabled
    public static List<brf_BatchApexErrorLog__c> failedJobs(){
        return [select JobApexClass__c, JobCreatedDate__c, JobErrors__c, JobId__c from brf_BatchApexErrorLog__c order by JobCreatedDate__c desc];
    }

    @AuraEnabled
    public static List<brf_BatchApexErrorLog__c> retryJob(Id retryJobId){
        brf_BatchableRetryJob.run(retryJobId);      
        return failedJobs();
    }
}