force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/InvoiceGenerationError__c.field-meta.xml
<CustomField>
    <fullName>InvoiceGenerationError__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Generation Error</label>
    <referenceTo>brf_BatchApexError__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceGenerationJob.cls
/**
 * Example job demonstrating the batch apex retry framework
 **/
public class InvoiceGenerationJob 
    implements Database.Batchable<SObject>, brf_BatchableErrorHandler
{
    public List<Order> start(Database.BatchableContext ctx) {
        return [select Id from Order 
                where EffectiveDate = THIS_WEEK and Invoiced__c != true
                order by Name];
    }

    public void execute(Database.BatchableContext ctx, List<SObject> scope) {
        // Invoice generation from given orders
        Set<Id> orderIds = new Map<Id, SObject>(scope).keySet();
        List<Invoice__c> invoices = new List<Invoice__c>();
        List<Order> orders = 
            [select Id, TotalAmount, Name from Order 
                where Id in :orderIds and Invoiced__c != true];
        for(Order order : orders) {
            produceSomeExceptions(order.Name);
            Invoice__c invoice = new Invoice__c();
            invoice.DueDate__c = System.today().addDays(30);
            invoice.Paid__c = false;
            invoice.Order__c = order.Id;
            invoice.Amount__c = order.TotalAmount;
            invoices.add(invoice);
            order.Invoiced__c = true;
        }
        insert invoices;
        update orders;
    }
    
    public void finish(Database.BatchableContext ctx) { }

    public void handleErrors(brf_BatchableError error) {
        // Update the effected orders with the error for further review
        List<String> orderIds = error.JobScope.split(',');
        List<Order> orders = [select Id from Order where Id in :orderIds];
        for(Order order : orders) {
            order.InvoiceGenerationError__c = error.Id;
        }
        update orders; 
    }

    // Produce some exceptions, some catchable, some not...
    private void produceSomeExceptions(String orderName) {
        switch on orderName {
           when 'Ref:100' {
               // Standard exception
               throw new InvoiceGenerationException('Order Ref:100 is invalid.');
           }
           when 'Ref:300' {
               // Divide by zero!
               Integer newAmount = 20 / 0;
           }
           when 'Ref:500' {
                // Limits exception
                for(Integer idx=0; idx<201; idx++) {
                    Order order = [select Id from Order limit 1];
                }
           }
        }
    }

    /**
     * InvoiceGenerationJob.run();
     **/
    public static Id run() {
        // Chunk size of 200 forces 5 batches given the sample data used in this example
        return Database.executeBatch(new InvoiceGenerationJob(), 200);
    }

    public class InvoiceGenerationException extends Exception {} 
}