force-brf/main/objects/brf_BatchApexError__c/brf_BatchApexError__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error</label>
    <nameField>
        <displayFormat>JOBE-{00000000}</displayFormat>
        <label>Batch Apex Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Errors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexError__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>AsyncApexJobId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/BatchApexErrorLog__c.field-meta.xml
<CustomField>
    <fullName>BatchApexErrorLog__c</fullName>
    <label>Batch Apex Error Log</label>
    <referenceTo>brf_BatchApexErrorLog__c</referenceTo>
    <relationshipLabel>Batch Apex Errors</relationshipLabel>
    <relationshipName>BatchApexErrors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/DoesExceedJobScopeMaxLength__c.field-meta.xml
<CustomField>
    <fullName>DoesExceedJobScopeMaxLength__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does Exceed Job Scope Max Length</label>
    <type>Checkbox</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobScope__c.field-meta.xml
<CustomField>
    <fullName>JobScope__c</fullName>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/brf_BatchApexErrorLog__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error Log</label>
    <nameField>
        <displayFormat>JOB-{00000000}</displayFormat>
        <label>Batch Apex Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>JobCreatedDate__c</fullName>
    <label>Job Created Date</label>
    <type>DateTime</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <externalId>true</externalId>
    <label>Job Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-brf/test/classes/brf_BatchApexErrorEventsTest.cls
@IsTest
private class brf_BatchApexErrorEventsTest {

    @IsTest
    private static void whenJobExceptionThenLogGeneratedAndHandlerCalled() {

        // Given
        Account testAccount = new Account(Name = 'Bad');
        insert testAccount;
        List<Account> testRecords = new List<Account> { testAccount };
        brf_BatchableErrorTestJob job = new brf_BatchableErrorTestJob(testRecords);

        // When
        Test.startTest();
        Id jobId = Database.executeBatch(job);
        try { Test.stopTest(); }
        catch(Exception ex) { /* don't fail this test if there were errors in the batch job - we want that */ }
        Test.getEventBus().deliver();

        // Then (failures captured)
        System.assertEquals(1, [select id from brf_BatchApexErrorLog__c].size());
        System.assertEquals('Test exception', [select Message__c from brf_BatchApexError__c][0].Message__c);
        System.assertEquals('Handled', [select Id, Name from Account where Id = :testAccount.Id].Name);
    }

    @IsTest
    private static void whenFailedJobLogThenRetrySuccessful() {

        // Given
        Account testAccount = new Account(Name = 'Good');
        insert testAccount;
        Id testJobId = '707S000000nKE4fIAG';
        brf_BatchApexErrorLog__c testJob = new brf_BatchApexErrorLog__c();
        testJob.JobApexClass__c = brf_BatchableErrorTestJob.class.getName();
        testJob.JobCreatedDate__c = System.today();
        testJob.JobId__c = testJobId;
        insert testJob;
        brf_BatchApexError__c testError = new brf_BatchApexError__c();
        testError.AsyncApexJobId__c = testJobId;
        testError.BatchApexErrorLog__c = testJob.Id;
        testError.DoesExceedJobScopeMaxLength__c = false;
        testError.ExceptionType__c = brf_BatchableErrorTestJob.TestJobException.class.getName();
        testError.JobApexClass__c = brf_BatchableErrorTestJob.class.getName();
        testError.JobScope__c = testAccount.Id;
        testError.Message__c = 'Test exception';
        testError.RequestId__c = null;
        testError.StackTrace__c = '';
        insert testError;

        // When
        Test.startTest();
        brf_BatchableRetryJob.run(testJobId);
        try { Test.stopTest(); }
        catch(Exception ex) { /* don't fail this test if there were errors in the batch job - we want that */ }
        Test.getEventBus().deliver();

        // Then (retry successful)
        System.assertEquals(0, [select id from brf_BatchApexErrorLog__c].size());
        System.assertEquals('All good', [select Id, Name from Account where Id = :testAccount.Id].Name);        
    }

    @IsTest
    private static void whenFailedJobLogThenRetryFailed() {

        // Given
        Id testJobId = '707S000000nKE4fIAG';
        Account testAccount = new Account(Name = 'Bad');
        insert testAccount;
        brf_BatchApexErrorLog__c testJob = new brf_BatchApexErrorLog__c();
        testJob.JobApexClass__c = brf_BatchableErrorTestJob.class.getName();
        testJob.JobCreatedDate__c = System.today();
        testJob.JobId__c = testJobId;
        insert testJob;
        brf_BatchApexError__c testError = new brf_BatchApexError__c();
        testError.AsyncApexJobId__c = testJobId;
        testError.BatchApexErrorLog__c = testJob.Id;
        testError.DoesExceedJobScopeMaxLength__c = false;
        testError.ExceptionType__c = brf_BatchableErrorTestJob.TestJobException.class.getName();
        testError.JobApexClass__c = brf_BatchableErrorTestJob.class.getName();
        testError.JobScope__c = testAccount.Id;
        testError.Message__c = 'Test exception';
        testError.RequestId__c = null;
        testError.StackTrace__c = '';
        insert testError;

        // When
        Test.startTest();
        brf_BatchableRetryJob.run(testJobId);
        try { Test.stopTest(); }
        catch(Exception ex) { /* don't fail this test if there were errors in the batch job - we want that */ }
        Test.getEventBus().deliver();

        // Then (retry failed)
        System.assertEquals(1, [select id from brf_BatchApexErrorLog__c].size());
        System.assertEquals('Test exception', [select Message__c from brf_BatchApexError__c][0].Message__c);
        System.assertEquals('Handled', [select Id, Name from Account where Id = :testAccount.Id].Name);
    }
}