force-brf/main/objects/brf_BatchApexError__c/brf_BatchApexError__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error</label>
    <nameField>
        <displayFormat>JOBE-{00000000}</displayFormat>
        <label>Batch Apex Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Errors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexError__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>AsyncApexJobId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/DoesExceedJobScopeMaxLength__c.field-meta.xml
<CustomField>
    <fullName>DoesExceedJobScopeMaxLength__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does Exceed Job Scope Max Length</label>
    <type>Checkbox</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobScope__c.field-meta.xml
<CustomField>
    <fullName>JobScope__c</fullName>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/classes/brf_BatchableError.cls
/**
 * Represents an error that occured processing a given chunk of items from a Batch Apex job
 *   See https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_batchapexerrorevent.htm
 **/
public class brf_BatchableError {
    
    public String ApexClassName;
    public Id Id;
    public Id AsyncApexJobId;
    public boolean DoesExceedJobScopeMaxLength;
    public String ExceptionType;
    public String JobScope;
    public String Message;
    public String RequestId;
    public String StackTrace;

    /**
     * Decomposes a persisted batch error into a BatchableError
     **/
    public static brf_BatchableError newInstance(brf_BatchApexError__c error) {
        brf_BatchableError newError = new brf_BatchableError();
        newError.ApexClassName = error.JobApexClass__c;
        newError.Id = error.Id;
        newError.AsyncApexJobId = error.AsyncApexJobId__c;
        newError.DoesExceedJobScopeMaxLength = error.DoesExceedJobScopeMaxLength__c;
        newError.ExceptionType = error.ExceptionType__c;
        newError.JobScope = error.JobScope__c;
        newError.Message = error.Message__c;
        newError.RequestId = error.RequestId__c;
        newError.StackTrace =error.StackTrace__c;
        return newError;
    }

    /**
     * BatchableErrors are used by the BatchableRetryJob which implements RaisesPlatformEvents.
     *   If errors occur during retry (execute method) this ensures this state is 
     *   passed on (via the JobScope field on BatchApexErrorEvent) so that the another retry can occur.
     **/      
    public override String toString() {
        return JSON.serialize(this, true);
    }
}