force-brf/main/objects/brf_BatchApexError__c/brf_BatchApexError__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error</label>
    <nameField>
        <displayFormat>JOBE-{00000000}</displayFormat>
        <label>Batch Apex Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Errors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexError__c/fields/AsyncApexJobId__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJobId__c</fullName>
    <label>AsyncApexJobId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/BatchApexErrorLog__c.field-meta.xml
<CustomField>
    <fullName>BatchApexErrorLog__c</fullName>
    <label>Batch Apex Error Log</label>
    <referenceTo>brf_BatchApexErrorLog__c</referenceTo>
    <relationshipLabel>Batch Apex Errors</relationshipLabel>
    <relationshipName>BatchApexErrors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/DoesExceedJobScopeMaxLength__c.field-meta.xml
<CustomField>
    <fullName>DoesExceedJobScopeMaxLength__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does Exceed Job Scope Max Length</label>
    <type>Checkbox</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>Exception Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/JobScope__c.field-meta.xml
<CustomField>
    <fullName>JobScope__c</fullName>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>Request Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexError__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/brf_BatchApexErrorLog__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error Log</label>
    <nameField>
        <displayFormat>JOB-{00000000}</displayFormat>
        <label>Batch Apex Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobApexClass__c.field-meta.xml
<CustomField>
    <fullName>JobApexClass__c</fullName>
    <label>Job Apex Class</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>JobCreatedDate__c</fullName>
    <label>Job Created Date</label>
    <type>DateTime</type>
</CustomField>

force-brf/main/objects/brf_BatchApexErrorLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <externalId>true</externalId>
    <label>Job Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-brf/main/classes/brf_BatchApexErrorEvents.cls
/**
 * Handles BatchApexErrorEvent events
 **/
public class brf_BatchApexErrorEvents {

    private List<BatchApexErrorEvent> events;

    public brf_BatchApexErrorEvents(List<BatchApexErrorEvent> events) { 
        this.events = events;
    }

    public void handle() {

        // Query associated AsyncApexJobs
        Set<Id> asyncApexJobIds = new Set<Id>();
        for(BatchApexErrorEvent evt : events){
            asyncApexJobIds.add(evt.AsyncApexJobId);
        }    
        // TODO: Use force-di to inject a test JobInfoResolver
        Map<Id, JobInfo> jobs = new RuntimeJobInfoResolver().resolveById(asyncApexJobIds);

        // Construct log records
        Map<Id, brf_BatchApexErrorLog__c> errorLogsById = new Map<Id, brf_BatchApexErrorLog__c>();
        Map<Id, List<brf_BatchApexError__c>> errorsById = new Map<Id, List<brf_BatchApexError__c>>();
        for(BatchApexErrorEvent evt : events){
            Id jobId = evt.AsyncApexJobId;
            JobInfo asyncApexJob = jobs.get(jobId);
            if(asyncApexJob!=null) {
                String apexClassName = asyncApexJob.ApexClassName;
                String jobScope = evt.JobScope;
                // From retry job?
                if(apexClassName == brf_BatchableRetryJob.class.getName()) {
                    // Adjust apex class and scope to reflect the orginal job not the retry job
                    brf_BatchableError retryBatchableError = (brf_BatchableError) JSON.deserialize(jobScope, brf_BatchableError.class);
                    apexClassName = retryBatchableError.ApexClassName;
                    jobScope = retryBatchableError.JobScope;
                }
                // Create Log?
                if(!errorLogsById.containsKey(jobId)) {
                    brf_BatchApexErrorLog__c errorLog = 
                        new brf_BatchApexErrorLog__c(
                            JobId__c = jobId,
                            JobApexClass__c = apexClassName,
                            JobCreatedDate__c = asyncApexJob.CreatedDate);
                    errorLogsById.put(jobId, errorLog);
                    errorsById.put(jobId, new List<brf_BatchApexError__c>());
                }
                // Add Error to Log
                errorsById.get(jobId).add(
                    new brf_BatchApexError__c(
                        AsyncApexJobId__c = jobId,
                        DoesExceedJobScopeMaxLength__c = evt.DoesExceedJobScopeMaxLength,
                        ExceptionType__c = evt.ExceptionType,
                        JobApexClass__c = apexClassName,
                        JobScope__c = jobScope,
                        Message__c = evt.Message,
                        RequestId__c = evt.RequestId,
                        StackTrace__c = evt.StackTrace));
            }
        }

        // Insert log records
        upsert errorLogsById.values() JobId__c;
        List<brf_BatchApexError__c> errors = new List<brf_BatchApexError__c>();
        for(Id jobId : errorLogsById.keySet()) {
            brf_BatchApexErrorLog__c log = errorLogsById.get(jobId);
            for(brf_BatchApexError__c error : errorsById.get(jobId)) {
                error.BatchApexErrorLog__c = log.Id;
                errors.add(error);
            }        
        }
        insert errors;

        // Allow the Batch Apex class a chance to handle the error
        for(brf_BatchApexError__c error : errors) {    
            Type apexJobClassType = Type.forName(error.JobApexClass__c);
            Object apexJob = apexJobClassType.newInstance();
            if(apexJob instanceof brf_BatchableErrorHandler) {
                brf_BatchableErrorHandler handler = (brf_BatchableErrorHandler) apexJob;
                handler.handleErrors(brf_BatchableError.newInstance(error));
            }
        }        
    }

    // Abstract queries made against AsyncApexJob to aid testability
    public abstract class JobInfoResolver {
        public abstract Map<Id, JobInfo> resolveById(Set<Id> jobIds);
    }
    public class RuntimeJobInfoResolver extends JobInfoResolver {
        public override Map<Id, JobInfo> resolveById(Set<Id> jobIds) {            
            Map<Id, JobInfo> jobsById = new Map<Id, JobInfo>();
            for(AsyncApexJob job : [select id, CreatedDate, ApexClass.Name from AsyncApexJob where Id IN :jobIds]) {
                JobInfo jobInfo = new JobInfo();
                jobInfo.Id = job.Id;
                jobInfo.ApexClassName = job.ApexClass.Name;
                jobInfo.CreatedDate = job.CreatedDate;
                jobsById.put(jobInfo.Id, jobInfo);
            }
            // TODO: Inject test impl of resolver via force-di, see handle method
            if(Test.isRunningTest()) {                
                JobInfo jobInfo = new JobInfo();
                jobInfo.Id = '707S000000nKE4fIAG';
                jobInfo.ApexClassName = brf_BatchableErrorTestJob.class.getName();
                jobInfo.CreatedDate = System.today();
                jobsById.put(jobInfo.Id, jobInfo);
            }
            return jobsById;
        }
    }
    public class JobInfo {
        public Id Id;
        public String ApexClassName;
        public DateTime CreatedDate;
    }
}